### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by Lakhankumawat** [adi-g15/cursesDisplay#1]
Please try to elaborate idea in ReadMe or anything like that so that others can get to know and they are able to commit or add smthg 🙂

**Comment by adi-g15** [comment]
Add kardunga 😅
Thanks bhai 😁👍

**Comment by Lakhankumawat** [comment]
Agar tum aache se kisi repo ko design karke esy to understand banaoge then you will definitely get stars and forks and followers 😁

**Comment by Lakhankumawat** [comment]
Ye issue close kar dena wese ye chat what's app pe bhi kar lete but sahi h 😂

**Comment by adi-g15** [comment]
Ho gaya add. Lekin abhi itna cheez hai hi nahi usme ki bataya jaye :grin:
